### ISSUE TITLE
Add tradeoffs section

### ISSUE THREAD

**Issue by brianorwhatever** [bitcoin-open-protocols-initiative/did-btco#3]
1. Cost will rise as Bitcoin transaction fees rise
2. Speed of updating a DID relies on inclusion into a block. Simple Payment Verification (SPV) may have been a solution to this issue however since Replace By Fee (RBF) was added to the network I believe it is no longer feasible.

**Comment by mikestaub** [comment]
There should also be a comparison to other BTC DID methods like https://github.com/decentralized-identity/ion

**Comment by brianorwhatever** [comment]
Thanks, I'm not too well versed in ION so would need help with the specifics. Are there any other tradeoffs outside of cost and speed that ION has over BTCO?

**Comment by mikestaub** [comment]
I think the main tradeoff is counterparty risk. With ordinals there is none because everything is on L1, but ION is similar to an L2 like Lightning as it uses sidetrees. https://identity.foundation/sidetree/spec/
